# Generated by Django 3.0.2 on 2020-01-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatinho', '0004_auto_20200110_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatinho',
            name='cor',
            field=models.CharField(choices=[('PRETO', 'Preto'), ('BRANCO', 'Branco'), ('PARDO', 'Pardo'), ('LARANJA', 'Laranja'), ('CINZA', 'Cinza'), ('TRICOLOR', 'Tricolor'), ('BEGE', 'Bege')], max_length=100),
        ),
    ]
