# Generated by Django 3.0.2 on 2020-01-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dono', '0001_initial'),
        ('gatinho', '0005_auto_20200115_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatinho',
            name='dono',
            field=models.ManyToManyField(to='dono.Dono'),
        ),
    ]
